# -*- coding: utf-8 -*-
"""SystemDS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M0zKg_dxxnWRURW3D_UGbdiCOM5Oa3on
"""

from systemds.context import SystemDSContext
import pandas as pd
from sklearn.model_selection import train_test_split
from systemds.operator.algorithm import lm

#open System DS Context
sds = SystemDSContext()

#input data in pandas
df = pd.read_csv(r"/content/DOHMH_New_York_City_Restaurant_Inspection_Results_20240319.csv")

X = df['Latitude']
y = df['SCORE']

#using sklearn to modify data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#using built in library to modify data set to usable form for regression
weights = lm(sds.from_pandas(X_train), sds.from_pandas(y_train))

# Stop SystemDS context
sds.close()